# This workflow use pylint:
#  - Install Python dependencies.
#  - Run pylint for each of the supported Python versions.
# Pylint will only fail without fixing any of the errors or warnings.

name: Pylint & Mypy

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11" ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies.
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r tools/requirements.txt
          python -m pip install -r tests/test-requirements.txt
          python -m pip install mypy pylint black types-beautifulsoup4 types-click
      - name: Running Black.
        uses: psf/black@stable
        with:
          options: "--check"
      - name: Running linter.
        run: |
          pylint --rcfile=.pylintrc --ignore=tests/ tools/
          pylint --rcfile=.pylintrc -d C0103,W0613 tests/
      - name: Running static types checker.
        run: |
          mypy .