name: Pytest.
on:
  pull_request:
    branches: [ "*" ]
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11" ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install UV
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
      - name: Install dependencies.
        run: |
          python -m uv pip install -r requirements.txt
          python -m uv pip install -r tests/test-requirements.txt
      - name: Running tests with pytest.
        run: |
          set -o pipefail
          pytest --cov=./ --cov-report=xml:coverage.xml --cov-report=term-missing
      - name: Upload coverage to Codecov.
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.xml